# Generated by Django 3.0.4 on 2020-05-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=80)),
            ],
        ),
    ]
