# Generated by Django 3.0.4 on 2020-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='telephone',
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(default='tettsa@gmail.com', max_length=60, verbose_name='email'),
        ),
    ]
