# Generated by Django 3.0.4 on 2020-05-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
    ]
